// AUTO-GENERATED by scripts/sandbox-dump.ts on 2026-04-25.
// Re-run: pnpm sandbox:regenerate
// Source: prod Neon — team=NE, season=2025, table=coaching_tendencies_weekly
// Edge-case augmenter applied (--no-augment to disable next time).

import type {
  CoachSegmentWithRollup,
  FourthDownDecision,
} from '@/lib/data/coaching';

export const coachSegments2025: CoachSegmentWithRollup[] = [
  {
    role: "HC",
    coachId: null,
    coachName: "Mike Vrabel",
    weekStart: 1,
    weekEnd: 18,
    rollup: {
      passRate1Short: 0.4090909090909091,
      passRate1Mid: 0.2222222222222222,
      passRate1Long: 0.44904772834440354,
      passRate2Short: 0.25980392156862747,
      passRate2Mid: 0.4630162321338792,
      passRate2Long: 0.7235209235209236,
      passRate3Short: 0.46960784313725495,
      passRate3Mid: 0.8774509803921569,
      passRate3Long: 0.9117647058823529,
      shotgunRate: 0.5463311379316939,
      playActionRate: 0,
      motionRate: 0,
      noHuddleRate: 0.021940486651389524,
      scoreLeadingBigPassRate: 0.43532631593780163,
      scoreLeadingSmallPassRate: 0.4803276293240987,
      scoreTiedPassRate: 0.4947819340676484,
      scoreTrailingSmallPassRate: 0.6244827863606145,
      scoreTrailingBigPassRate: 0.7698412698412699,
      secondsPerSnap: 39.294117647058826,
      personnelTopGroups: [
        {
          grouping: "1 C, 2 G, 1 QB, 1 RB, 2 T, 1 TE, 3 WR",
          share: 0.35942313025056843,
        },
        {
          grouping: "1 C, 2 G, 1 QB, 1 RB, 2 T, 2 TE, 2 WR",
          share: 0.14968659953222901,
        },
        {
          grouping: "2 C, 1 G, 1 QB, 1 RB, 2 T, 1 TE, 3 WR",
          share: 0.1295474838387085,
        },
        {
          grouping: "1 C, 1 FB, 2 G, 1 QB, 1 RB, 2 T, 1 TE, 2 WR",
          share: 0.07015974252204235,
        },
        {
          grouping: "2 C, 1 G, 1 QB, 1 RB, 2 T, 2 TE, 2 WR",
          share: 0.047598615534970405,
        },
      ],
      blitzRate: null,
    },
  },
  {
    role: "OC",
    coachId: null,
    coachName: "Josh McDaniels",
    weekStart: 1,
    weekEnd: 9,
    rollup: {
      passRate1Short: 0.4090909090909091,
      passRate1Mid: 0.2222222222222222,
      passRate1Long: 0.44904772834440354,
      passRate2Short: 0.25980392156862747,
      passRate2Mid: 0.4630162321338792,
      passRate2Long: 0.7235209235209236,
      passRate3Short: 0.46960784313725495,
      passRate3Mid: 0.8774509803921569,
      passRate3Long: 0.9117647058823529,
      shotgunRate: 0.5463311379316939,
      playActionRate: 0,
      motionRate: 0,
      noHuddleRate: 0.021940486651389524,
      scoreLeadingBigPassRate: 0.43532631593780163,
      scoreLeadingSmallPassRate: 0.4803276293240987,
      scoreTiedPassRate: 0.4947819340676484,
      scoreTrailingSmallPassRate: 0.6244827863606145,
      scoreTrailingBigPassRate: 0.7698412698412699,
      secondsPerSnap: 39.294117647058826,
      personnelTopGroups: [
        {
          grouping: "1 C, 2 G, 1 QB, 1 RB, 2 T, 1 TE, 3 WR",
          share: 0.35942313025056843,
        },
        {
          grouping: "1 C, 2 G, 1 QB, 1 RB, 2 T, 2 TE, 2 WR",
          share: 0.14968659953222901,
        },
        {
          grouping: "2 C, 1 G, 1 QB, 1 RB, 2 T, 1 TE, 3 WR",
          share: 0.1295474838387085,
        },
        {
          grouping: "1 C, 1 FB, 2 G, 1 QB, 1 RB, 2 T, 1 TE, 2 WR",
          share: 0.07015974252204235,
        },
        {
          grouping: "2 C, 1 G, 1 QB, 1 RB, 2 T, 2 TE, 2 WR",
          share: 0.047598615534970405,
        },
      ],
      blitzRate: null,
    },
  },
  {
    role: "OC",
    coachId: null,
    coachName: "[augmented] mid-season replacement",
    weekStart: 10,
    weekEnd: 18,
    rollup: {
      passRate1Short: 0.4090909090909091,
      passRate1Mid: 0.2222222222222222,
      passRate1Long: 0.44904772834440354,
      passRate2Short: 0.25980392156862747,
      passRate2Mid: 0.4630162321338792,
      passRate2Long: 0.7235209235209236,
      passRate3Short: 0.46960784313725495,
      passRate3Mid: 0.8774509803921569,
      passRate3Long: 0.9117647058823529,
      shotgunRate: 0.5463311379316939,
      playActionRate: 0,
      motionRate: 0,
      noHuddleRate: 0.021940486651389524,
      scoreLeadingBigPassRate: 0.43532631593780163,
      scoreLeadingSmallPassRate: 0.4803276293240987,
      scoreTiedPassRate: 0.4947819340676484,
      scoreTrailingSmallPassRate: 0.6244827863606145,
      scoreTrailingBigPassRate: 0.7698412698412699,
      secondsPerSnap: 39.294117647058826,
      personnelTopGroups: [
        {
          grouping: "1 C, 2 G, 1 QB, 1 RB, 2 T, 1 TE, 3 WR",
          share: 0.35942313025056843,
        },
        {
          grouping: "1 C, 2 G, 1 QB, 1 RB, 2 T, 2 TE, 2 WR",
          share: 0.14968659953222901,
        },
        {
          grouping: "2 C, 1 G, 1 QB, 1 RB, 2 T, 1 TE, 3 WR",
          share: 0.1295474838387085,
        },
        {
          grouping: "1 C, 1 FB, 2 G, 1 QB, 1 RB, 2 T, 1 TE, 2 WR",
          share: 0.07015974252204235,
        },
        {
          grouping: "2 C, 1 G, 1 QB, 1 RB, 2 T, 2 TE, 2 WR",
          share: 0.047598615534970405,
        },
      ],
      blitzRate: null,
    },
  },
  {
    role: "DC",
    coachId: null,
    coachName: "Terrell Williams",
    weekStart: 1,
    weekEnd: 18,
    rollup: {
      passRate1Short: null,
      passRate1Mid: null,
      passRate1Long: null,
      passRate2Short: null,
      passRate2Mid: null,
      passRate2Long: null,
      passRate3Short: null,
      passRate3Mid: null,
      passRate3Long: null,
      shotgunRate: null,
      playActionRate: null,
      motionRate: null,
      noHuddleRate: null,
      scoreLeadingBigPassRate: null,
      scoreLeadingSmallPassRate: null,
      scoreTiedPassRate: null,
      scoreTrailingSmallPassRate: null,
      scoreTrailingBigPassRate: null,
      secondsPerSnap: null,
      personnelTopGroups: [],
      blitzRate: 0.10097373264490361,
    },
  },
];

export const fourthDownDecisions2025: FourthDownDecision[] = [
  {
    week: 5,
    wpBoostGo: 0.018,
    wentForIt: true,
    goRecommended: true,
    resultYards: 7,
  },
  {
    week: 9,
    wpBoostGo: 0.011,
    wentForIt: true,
    goRecommended: true,
    resultYards: -2,
  },
  {
    week: 13,
    wpBoostGo: -0.012,
    wentForIt: true,
    goRecommended: false,
    resultYards: 3,
  },
  {
    week: 15,
    wpBoostGo: 0.057,
    wentForIt: true,
    goRecommended: true,
    resultYards: 12,
  },
];

export type { TendencyRollup } from '@/lib/data/coaching';
