// AUTO-GENERATED by scripts/sandbox-dump.ts on 2026-04-25.
// Re-run: pnpm sandbox:regenerate
// Source: prod Neon — team=NE, season=2025, table=team_phase_season + games
// Edge-case augmenter applied (--no-augment to disable next time).

import type { TeamSeasonOverview, GameResult } from '@/lib/data/team';

export const teamOverview2025: TeamSeasonOverview = {
  season: 2025,
  record: {
    wins: 14,
    losses: 3,
    ties: 0,
  },
  pointDiff: 170,
  currentSeasonRank: 2,
  currentSeasonEpa: 0.20295905698130723,
  prevSeasonRank: 27,
};

export const recentGames2025: GameResult[] = [
  {
    gameId: "2025_18_MIA_NE",
    season: 2025,
    week: 18,
    gameDate: new Date('2026-01-04T00:00:00.000Z'),
    opponent: "MIA",
    isHome: true,
    teamScore: 38,
    oppScore: 10,
    teamEpaPerPlay: 0.35990873299846027,
    oppEpaPerPlay: -0.34409286922429466,
  },
  {
    gameId: "2025_17_NE_NYJ",
    season: 2025,
    week: 17,
    gameDate: new Date('2025-12-28T00:00:00.000Z'),
    opponent: "NYJ",
    isHome: false,
    teamScore: 42,
    oppScore: 10,
    teamEpaPerPlay: 0.48764402833789583,
    oppEpaPerPlay: -0.19830819677414527,
  },
  {
    gameId: "2025_16_NE_BAL",
    season: 2025,
    week: 16,
    gameDate: new Date('2025-12-21T00:00:00.000Z'),
    opponent: "BAL",
    isHome: false,
    teamScore: 28,
    oppScore: 24,
    teamEpaPerPlay: 0.21092189880171036,
    oppEpaPerPlay: 0.10519732781124119,
  },
  {
    gameId: "2025_15_BUF_NE",
    season: 2025,
    week: 15,
    gameDate: new Date('2025-12-14T00:00:00.000Z'),
    opponent: "BUF",
    isHome: true,
    teamScore: 31,
    oppScore: 35,
    teamEpaPerPlay: 0.24429784937200227,
    oppEpaPerPlay: 0.2610677966958974,
  },
  {
    gameId: "2025_13_NYG_NE",
    season: 2025,
    week: 13,
    gameDate: new Date('2025-12-01T00:00:00.000Z'),
    opponent: "NYG",
    isHome: true,
    teamScore: 33,
    oppScore: 15,
    teamEpaPerPlay: 0.16901200826397503,
    oppEpaPerPlay: -0.1300847243060762,
  },
  {
    gameId: "__SANDBOX_FIXTURE__tie_game",
    season: 2025,
    week: 12,
    gameDate: new Date('2025-11-23T00:00:00.000Z'),
    opponent: "CIN",
    isHome: false,
    teamScore: 20,
    oppScore: 20,
    teamEpaPerPlay: 0.05,
    oppEpaPerPlay: 0.05,
  },
];
