"""Pydantic models mirroring db/schema.ts.

Keep in sync with `db/schema.ts`. The E2-00b schema-sync test
(etl/tests/test_schema_sync.py) diffs model fields against a JSON export of
the Drizzle schema and warns on drift.

Shape conventions:
  - Field names are snake_case and match the Drizzle column names verbatim.
  - Nullable columns use `T | None` with a default of `None`.
  - Generated columns (is_redzone, is_third_down) are included as readable
    but never used on write — they're populated by Postgres.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from etl.constants import PHASES

Status = Literal["running", "ok", "failed", "heartbeat"]
SeasonType = Literal["REG", "POST"]
Phase = Literal[
    "pass_offense",
    "rush_offense",
    "overall",
    "pass_defense",
    "run_defense",
    "redzone_offense",
    "redzone_defense",
    "third_down_offense",
    "third_down_defense",
    "explosive_offense",
    "explosive_defense",
    "special_teams",
]

# Belt-and-suspenders: the Literal above and the PHASES tuple must match.
assert set(Phase.__args__) == set(PHASES), "Phase Literal drifted from PHASES tuple"


class MetaRefresh(BaseModel):
    """Mirror of db/schema.ts `meta_refresh`."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    id: int | None = None
    started_at: datetime
    completed_at: datetime | None = None
    status: Status
    season: int | None = None
    week: int | None = None
    source_version: str | None = Field(default=None, max_length=40)
    row_counts: dict[str, int] | None = None
    error_text: str | None = None


class Game(BaseModel):
    """Mirror of db/schema.ts `games`."""

    model_config = ConfigDict(extra="forbid")

    game_id: str
    season: int
    week: int
    season_type: SeasonType
    home_team: str = Field(max_length=3)
    away_team: str = Field(max_length=3)
    home_score: int | None = None
    away_score: int | None = None
    game_date: date
    completed: bool = False
    posteam_epa: float | None = None
    defteam_epa: float | None = None


class Play(BaseModel):
    """Mirror of db/schema.ts `plays`. ~40 columns, union of E3/E4/E5 needs."""

    model_config = ConfigDict(extra="forbid")

    # Primary key
    game_id: str
    play_id: int

    # Partition cols
    season: int
    week: int
    season_type: SeasonType

    # Team + situation
    posteam: str | None = Field(default=None, max_length=3)
    defteam: str | None = Field(default=None, max_length=3)
    down: int | None = None
    ydstogo: int | None = None
    yardline_100: int | None = None
    play_type: str | None = Field(default=None, max_length=16)
    yards_gained: int | None = None

    # nflfastR advanced
    epa: float | None = None
    cpoe: float | None = None
    success: bool | None = None
    wp: float | None = None

    # Play-type flags
    qb_dropback: bool | None = None
    qb_kneel: bool | None = None
    qb_spike: bool | None = None
    two_point_attempt: bool | None = None
    pass_attempt: bool | None = None
    rush_attempt: bool | None = None
    pass_length: str | None = Field(default=None, max_length=8)
    air_yards: int | None = None

    # Generated by Postgres (read-only on Python side)
    is_redzone: bool | None = None
    is_third_down: bool | None = None

    # Set during load
    is_explosive_pass: bool | None = None
    is_explosive_run: bool | None = None
    special_teams_play: bool | None = None

    # E4-dep
    qb_hit: bool | None = None
    sack: bool | None = None
    was_pressure: bool | None = None
    number_of_pass_rushers: int | None = None

    # E5-dep
    shotgun: bool | None = None
    no_huddle: bool | None = None
    pre_snap_motion: bool | None = None
    play_action: bool | None = None
    personnel_offense: str | None = Field(default=None, max_length=16)
    personnel_defense: str | None = Field(default=None, max_length=16)
    defenders_in_box: int | None = None

    # E5-nfl4th-dep
    score_differential: int | None = None
    game_seconds_remaining: int | None = None
    posteam_timeouts_remaining: int | None = None
    defteam_timeouts_remaining: int | None = None
    roof: str | None = Field(default=None, max_length=12)
    surface: str | None = Field(default=None, max_length=16)


class TeamPhaseWeekly(BaseModel):
    """Mirror of db/schema.ts `team_phase_weekly`."""

    model_config = ConfigDict(extra="forbid")

    team: str = Field(max_length=3)
    season: int
    week: int
    phase: Phase
    plays: int
    epa_per_play: float | None = None
    success_rate: float | None = None
    rank: int | None = None
    percentile: float | None = None
    insufficient_sample: bool = False
    updated_at: datetime | None = None


class TeamPhaseSeason(BaseModel):
    """Mirror of db/schema.ts `team_phase_season`."""

    model_config = ConfigDict(extra="forbid")

    team: str = Field(max_length=3)
    season: int
    phase: Phase
    plays: int
    epa_per_play: float | None = None
    success_rate: float | None = None
    rank: int | None = None
    percentile: float | None = None
    insufficient_sample: bool = False
    updated_at: datetime | None = None
